### ISSUE TITLE
我在使用中出现了这个报错

### ISSUE THREAD

**Issue by lzhbhlrPython** [kangvcar/InfoSpider#12]
```
Traceback (most recent call last):
  File "D:\Working\Codes\InfoSpider\tools\main.py", line 34, in <module>
    from alipay.main import ASpider
ModuleNotFoundError: No module named 'alipay.main'
```

**Comment by users043** [comment]
安装时遇到如下问题
PS D:\pip\InfoSpider-master\tools> python3 main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
PS D:\pip\InfoSpider-master\tools>


 ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; 


    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize;

**Comment by lzhbhlrPython** [comment]
Maybe You should use *Wxpython*?
Try to
```bash
pip install wxpython
```

**Comment by kangvcar** [comment]
# [购买服务](https://mianbaoduo.com/o/bread/aZiTlJo=)

- InfoSpider 最新维护版本
- 更全面的个人数据分析
- 免去安装程序的所有依赖环境，便捷，适合小白
- 已打包好的程序，双击即可运行程序
- 手把手教你如何打包 InfoSpider
- 开发者一对一技术支持

[![](https://camo.githubusercontent.com/83014e1457fe03f1ab7b5ed5438489fbeaa97f1c/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31302f32302f4952624c7a456d4276394b747770342e6a7067)](https://mianbaoduo.com/o/bread/aZiTlJo=)
