### ISSUE TITLE
？

### ISSUE THREAD

**Issue by locatomlion** [kangvcar/InfoSpider#13]
![image](https://user-images.githubusercontent.com/70186641/91119003-cf0dfb80-e6c4-11ea-80cf-e1a3a7dce54d.png)

**Comment by MiguangSun** [comment]
我有同样的错

**Comment by kangvcar** [comment]
请参照 https://github.com/kangvcar/InfoSpider/issues/1#issuecomment-677471766

**Comment by kangvcar** [comment]
# [购买服务](https://mianbaoduo.com/o/bread/aZiTlJo=)

- InfoSpider 最新维护版本
- 更全面的个人数据分析
- 免去安装程序的所有依赖环境，便捷，适合小白
- 已打包好的程序，双击即可运行程序
- 手把手教你如何打包 InfoSpider
- 开发者一对一技术支持

[![](https://camo.githubusercontent.com/83014e1457fe03f1ab7b5ed5438489fbeaa97f1c/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31302f32302f4952624c7a456d4276394b747770342e6a7067)](https://mianbaoduo.com/o/bread/aZiTlJo=)
