### ISSUE TITLE
没有微博数据源吗

### ISSUE THREAD

**Issue by TianYongwei** [kangvcar/InfoSpider#16]
## Bug Report

**Description**: [Description of the issue]

**Expected behavior**: [What should happen]

**Current behavior**: [What happpens instead of the expected behavior]

**Steps to Reproduce**:

1. [First Step]
2. [Second Step]
3. [and so on ¡­]

**Reproduce how often**: [What percentage of the time does it reproduce?]

**Possible solution**: [Not obligatory, but suggest a fix/reason for the bug]

**Context (Environment)**:[The code version, python version, operating system or other software/libs you use]

## Additional Information

[Any other useful information about the problem].

**Comment by kangvcar** [comment]
目前v1.0版本没有weibo数据源
计划在v2.0版本加入，敬请期待
