### ISSUE TITLE
爬取失败

### ISSUE THREAD

**Issue by constantine008** [kangvcar/InfoSpider#18]
systeminfo:
![image](https://user-images.githubusercontent.com/20673815/92542066-5ee1a700-f27a-11ea-8867-55682859fd92.png)

C:\Users\stsg0>python -V
Python 3.7.9

C:\Users\stsg0>pip -V
pip 20.2.3 from c:\users\stsg0\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)

1.点击QQ邮箱，没有弹出输入框，右下角直接提示爬取失败
![image](https://user-images.githubusercontent.com/20673815/92541917-e5e24f80-f279-11ea-8b76-f053ddaab1f5.png)
2.点击网易邮箱，控制台报错
![image](https://user-images.githubusercontent.com/20673815/92541965-10cca380-f27a-11ea-9b46-de5bea99a4cb.png)

chromeDriver已经启动了
![image](https://user-images.githubusercontent.com/20673815/92542007-3194f900-f27a-11ea-8f7d-aef906346fd9.png)

**Comment by liyuazi** [comment]
same problem，直接右下角爬取失败，我觉得我的是Chromedriver启动失败，测试下！

**Comment by kangvcar** [comment]
# [购买服务](https://mianbaoduo.com/o/bread/aZiTlJo=)

- InfoSpider 最新维护版本
- 更全面的个人数据分析
- 免去安装程序的所有依赖环境，便捷，适合小白
- 已打包好的程序，双击即可运行程序
- 手把手教你如何打包 InfoSpider
- 开发者一对一技术支持

[![](https://camo.githubusercontent.com/83014e1457fe03f1ab7b5ed5438489fbeaa97f1c/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31302f32302f4952624c7a456d4276394b747770342e6a7067)](https://mianbaoduo.com/o/bread/aZiTlJo=)
