### ISSUE TITLE
QQ空间可以生成相册吗

### ISSUE THREAD

**Issue by tomxin7** [kangvcar/InfoSpider#20]
QQ空间可以生成相册吗

**Comment by kangvcar** [comment]
@tomxin7 
没太懂你的需求呀？
爬取QQ空间的相册？

**Comment by tomxin7** [comment]
类似于朋友圈相册，就是把QQ的动态导出来~~

**Comment by kangvcar** [comment]
@tomxin7 可以的哈，原本有这个功能，后来觉得需求不大给删除了，2.0版本会重新加入。
