### ISSUE TITLE
bilibili 爬取https://api.bilibili.com/x/v2/history?pn=4&ps=300&jsonp=jsonp 获取到data:"" 

### ISSUE THREAD

**Issue by nepiedg** [kangvcar/InfoSpider#21]
获取到data= null 导致程序异常,无法导出
bilibili/main.py

if len(result['data']) == 0:

**Comment by nepiedg** [comment]
获取到data= null 导致程序异常,无法导出

**Comment by kangvcar** [comment]
@nepiedg 已修复

**Comment by kangvcar** [comment]
# [购买服务](https://mianbaoduo.com/o/bread/aZiTlJo=)

- InfoSpider 最新维护版本
- 更全面的个人数据分析
- 免去安装程序的所有依赖环境，便捷，适合小白
- 已打包好的程序，双击即可运行程序
- 手把手教你如何打包 InfoSpider
- 开发者一对一技术支持

[![](https://camo.githubusercontent.com/83014e1457fe03f1ab7b5ed5438489fbeaa97f1c/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31302f32302f4952624c7a456d4276394b747770342e6a7067)](https://mianbaoduo.com/o/bread/aZiTlJo=)
