### ISSUE TITLE
【更新建议】可以支持人人网吗

### ISSUE THREAD

**Issue by ShaoZC** [kangvcar/InfoSpider#23]
## Bug Report

**Description**: [Description of the issue]

**Expected behavior**: [What should happen]

**Current behavior**: [What happpens instead of the expected behavior]

**Steps to Reproduce**:

1. [First Step]
2. [Second Step]
3. [and so on ¡­]

**Reproduce how often**: [What percentage of the time does it reproduce?]

**Possible solution**: [Not obligatory, but suggest a fix/reason for the bug]

**Context (Environment)**:[The code version, python version, operating system or other software/libs you use]

## Additional Information

[Any other useful information about the problem].

**Comment by kangvcar** [comment]
@ShaoZC 人人网的用户比较少了，下一版本考虑加入。

**Comment by ShaoZC** [comment]
> @ShaoZC 人人网的用户比较少了，下一版本考虑加入。

感谢，之前有人开发过类似爬虫。怀旧粉丝还是很多的，像2010年之前的大学生，青春的记忆都在上面。
