### ISSUE TITLE
现在一些网站都会有反爬措施，其中 webdriver 的检查是很基本的一项。如何规避反爬？

### ISSUE THREAD

**Issue by socay1** [kangvcar/InfoSpider#24]
1. 能规避反爬保护吗？
2. 能够链接跟进吗？

**Comment by kangvcar** [comment]
@socay1 反爬虫的手段和策略非常多，具体需要对网站进行反复测试，参见 [https://www.zhihu.com/question/50738719](https://www.zhihu.com/question/50738719)
