### ISSUE TITLE
和Ray项目的集成？

### ISSUE THREAD

**Issue by zhe-thoughts** [kangvcar/InfoSpider#26]
请问有没有兴趣和Ray项目集成，来实现多核/多节点的加速？

参见：https://github.com/raulchen/ray-intro-cn/blob/master/python/demo.py
我还写了一个很简单的并行github爬虫：https://github.com/zhe-thoughts/raytools/blob/master/github_analyzer/github_stargazers.py

**Comment by kangvcar** [comment]
@zhe-thoughts 谢谢您的推荐，你的Ray项目非常棒。
