### ISSUE TITLE
挺不错的，但是为什么要用tk作为gui界面， 我很奇怪。

### ISSUE THREAD

**Issue by shalouzaixiayu** [kangvcar/InfoSpider#28]
刚在公众号推送看到你的开源， 确实很不错， 很全也挺美观的， 但是作为一个开发来说，我觉得这个工具作用没那么高， 但是对应你的标题，收集你自己的个性信息，又非常合情合理了， 另外其实没必要用tkinter作为GUI界面的创造，tk有的时候会崩溃的，不是很好使，最好建议是开发一个web端口， 那就很好了，good !

**Comment by kangvcar** [comment]
@shalouzaixiayu 英雄所见略同，计划在v2.0版本对项目进行重构，提供web端操作与数据可视化，以适配多平台。

**Comment by GangLiCN** [comment]
简单一点的话就是提供restful API接口，在浏览器中返回用户需要的信息，再复杂一点可以增加一个自定义配置的界面，对各种不同类型的网站信息的爬取选项和输出选项进行用户自定义，这样可以做到个性化的展示。

**Comment by kangvcar** [comment]
@GangLiCN 您的提议非常棒，谢谢您！

**Comment by gengyanlei** [comment]
不能任意爬取我想要的信息，只爬个人的没啥意思。要的就是爬其它数据，哈哈

**Comment by kangvcar** [comment]
@gengyanlei 下一版本会提供自定义数据项爬取功能
