### ISSUE TITLE
这个不犯法吗？

### ISSUE THREAD

**Issue by FrankCy** [kangvcar/InfoSpider#36]
## Bug Report

**Description**: [Description of the issue]

**Expected behavior**: [What should happen]

**Current behavior**: [What happpens instead of the expected behavior]

**Steps to Reproduce**:

1. [First Step]
2. [Second Step]
3. [and so on ¡­]

**Reproduce how often**: [What percentage of the time does it reproduce?]

**Possible solution**: [Not obligatory, but suggest a fix/reason for the bug]

**Context (Environment)**:[The code version, python version, operating system or other software/libs you use]

## Additional Information

[Any other useful information about the problem].

**Comment by FrankCy** [comment]
你都可以开卖了？？？

**Comment by kangvcar** [comment]
@FrankCy 一个获取自己信息的工具箱，你怎么定义的违法？

**Comment by FrankCy** [comment]
> @FrankCy 一个获取自己信息的工具箱，你怎么定义的违法？

是呢，没事，挺好的，加油
