### ISSUE TITLE
安装依赖时报错，临时解决办法

### ISSUE THREAD

**Issue by xia0sheng** [kangvcar/InfoSpider#57]
安装第一个依赖时报错：UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 2621: illegal multibyte sequence
解决办法，替换版本
matplotlib==3.2.0 为 matplotlib==3.6.0

应该是安装numpy的时候提示要安装c++ 14以上的
解决方法，先安装conda  然后
conda install libpython m2w64-toolchain -c msys2

**Comment by kangvcar** [comment]
👍

**Comment by xia0sheng** [comment]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 195: illegal multibyte sequence
解决方法：
找到相应代码处 在gbk后面添加 'ignore'
修改完  实例：data = {
                    'orderWareIds': '{}'.format(
                        re.findall(r"ORDER_CONFIG\['orderWareIds'\]='([\d,]+)'", resp.content.decode('gbk', 'ignore'))[0]),

**Comment by xia0sheng** [comment]
2022年11月10日 最终版的依赖包如下，可以正常运行程序

beautifulsoup4==4.9.1
certifi==2022.9.24
chardet==3.0.4
click==8.1.3
colorama==0.4.6
contourpy==1.0.6
cssselect==1.2.0
cycler==0.11.0
et-xmlfile==1.1.0
fonttools==4.38.0
future==0.18.2
idna==2.8
itchat==1.2.32
jdcal==1.4.1
Jinja2==3.1.2
joblib==1.2.0
kiwisolver==1.4.4
lxml==4.9.1
MarkupSafe==2.1.1
matplotlib==3.6.0
nltk==3.6.6
numpy==1.23.4
openpyxl==3.0.4
packaging==21.3
pandas==1.5.1
Pillow==9.0.1
prettytable==3.5.0
pyecharts==1.7.1
pyparsing==3.0.9
pypng==0.20220715.0
PyQRCode==1.2.1
pyquery==1.4.0
python-dateutil==2.8.1
pytz==2022.6
regex==2022.10.31
requests==2.22.0
selenium==3.141.0
simplejson==3.17.6
six==1.16.0
soupsieve==2.3.2.post1
tqdm==4.47.0
urllib3==1.25.11
wcwidth==0.2.5
wxpy==0.3.9.8
wxPython==4.2.0
XlsxWriter==1.2.9

**Comment by xia0sheng** [comment]
另外还遇到个错误  就是下载了  chromedriver  但是运行程序时还是提示找不到chromedriver
解决方法：
1、将下载的chromedriver所在的目录添加到电脑的环境变量中
2、复制一份chromedriver到python所在的目录里，我是用的虚拟环境  python-m venv env   所以我复制了一份到env/Scripts/ 这个目录下   程序就可以正常运行了

**Comment by xia0sheng** [comment]
最后非常感谢作者的开源   希望我遇到的问题对大家有所帮助

**Comment by kangvcar** [comment]
@xia0sheng 很高兴你能把遇到问题的解决方法分享出来，由于爬虫项目具有时效性，想邀请你一起来开发维护这个项目。

**Comment by kangvcar** [comment]
> > @xia0sheng 很高兴你能把遇到问题的解决方法分享出来，由于爬虫项目具有时效性，想邀请你一起来开发维护这个项目。
> 
> 非常感谢你的邀请 不是我不想参与哈 而是实在是技术水平有限 感觉我的技术水平仅仅能够让你的脚本跑起来。。。。。。

了解了，同时欢迎你随时提交 PR

**Comment by kangvcar** [comment]
> > > @xia0sheng 很高兴你能把遇到问题的解决方法分享出来，由于爬虫项目具有时效性，想邀请你一起来开发维护这个项目。
> > 
> > 
> > 非常感谢你的邀请 不是我不想参与哈 而是实在是技术水平有限 感觉我的技术水平仅仅能够让你的脚本跑起来。。。。。。
> 
> 了解了，同时欢迎你随时提交 PR

@xia0sheng  我们正在尝试把项目进行重新开发，作为 Chrome Extension 的方式运行，只要有浏览器就能使用了，无需安装一堆 Python 依赖等等。

**Comment by xia0sheng** [comment]
> > > > @xia0sheng 很高兴你能把遇到问题的解决方法分享出来，由于爬虫项目具有时效性，想邀请你一起来开发维护这个项目。
> > > 
> > > 
> > > 非常感谢你的邀请 不是我不想参与哈 而是实在是技术水平有限 感觉我的技术水平仅仅能够让你的脚本跑起来。。。。。。
> > 
> > 
> > 了解了，同时欢迎你随时提交 PR
> 
> @xia0sheng 我们正在尝试把项目进行重新开发，作为 Chrome Extension 的方式运行，只要有浏览器就能使用了，无需安装一堆 Python 依赖等等。

👍🏻

**Comment by malone6** [comment]
> > > > @xia0sheng 很高兴你能把遇到问题的解决方法分享出来，由于爬虫项目具有时效性，想邀请你一起来开发维护这个项目。
> > > 
> > > 
> > > 非常感谢你的邀请 不是我不想参与哈 而是实在是技术水平有限 感觉我的技术水平仅仅能够让你的脚本跑起来。。。。。。
> > 
> > 
> > 了解了，同时欢迎你随时提交 PR
> 
> @xia0sheng 我们正在尝试把项目进行重新开发，作为 Chrome Extension 的方式运行，只要有浏览器就能使用了，无需安装一堆 Python 依赖等等。

chrome插件形式的开发进度是什么样了， 这个python的依赖太难装了， 作为一个python老手在win上搞这个项目好久还没运行起来
